Add GetBaseReport Command Handling to OCPP 2.0.1 Server
SAP/e-mobility-charging-stations-simulator pull request #1041
Opened 2024-06-05 14:17 UTC by syuusei3

This pull request adds support for handling the GetBaseReport command in our OCPP 2.0.1 server implementation, addressing issue #39.

Changes include:
- Creation of a new ChargePoint class that supports OCPP 2.0.1
- Implementation of handlers for BootNotification and GetBaseReport commands
- Improvement of WebSocket connection handling
- Update to the main server function to create a WebSocket server

Please review and provide feedback.

2024-06-07 19:53 UTC, Kostasn2 approved these changes

2024-06-07 19:55 UTC, TheReaperGR approved these changes
seems good

2024-06-10 11:20 UTC, jerome-benoit requested changes

2024-06-10 11:20 UTC, jerome-benoit commented on tests/ocpp-server/server.py
> +    @on('BootNotification')
More "stub" OCPP command handlers will be needed to allow the simulator to work. 
Have you tested it with the core in the PR?

2024-06-10 11:20 UTC, jerome-benoit commented on tests/ocpp-server/server.py
> +        '0.0.0.0',  # Listen on all available interfaces.
Please listen by default on the loopback to avoid security issues while developing.

2024-06-10 11:20 UTC, jerome-benoit commented on tests/ocpp-server/server.py
> +        subprotocols=['ocpp2.0.1']  # Specify the OCPP 2.0.1 subprotocol.
Please also allow the previous ocpp2.0 subprotocol

2024-06-10 11:20 UTC, jerome-benoit commented on tests/ocpp-server/README.md
> +pip install websockets ocpp
Have you already implemented the python virtualenv with pipenv? Requiring to install globally python packages for development is not required nowadays.

2024-06-10 16:54 UTC, jerome-benoit commented
I merge the PR as it, then address the review comments in the main branch directly.

2024-06-10 16:54 UTC, merged